### PR TITLE
addpatch: libhangul 0.1.0-5

### PR DESCRIPTION
**Pull request by qyl27**
The outdated configure file issue was reported in https://github.com/libhangul/libhangul/issues/83 .

### CODE REVIEW

**Comment by Xeonacid** [comment]
The source seems at https://github.com/libhangul/libhangul now.

**Comment by OctopusET** [comment]
duplicate of #3931 ?

**Comment by qyl27** [comment]
> duplicate of #3931 ?

Ah, yes, but I haven't seen anyone assigned this package on the status page.

**Comment by XieJiSS** [comment]
probably we should close this as dup for now

**Pull request closed without merging**
