### PR TITLE
addpkg:skktools

### PR DESCRIPTION
**Pull request by XiePengHan**
I am in contact with the upstream, and I will comment on the results here

### CODE REVIEW

**Comment by XiePengHan** [comment]
> 我正在与上游联系，我将在这里对结果发表评论

I have already reported it to the upstream.

**Comment by r-value** [comment]
Please leave a link here as a reference if possible

**Comment by XiePengHan** [comment]
> 如果可能的话，请在这里留下链接作为参考

https://github.com/skk-dev/skktools/issues/25
Thank you for your reminder. I have provided some simple descriptions.

**Comment by XiePengHan** [comment]
> Please leave a link here as a reference if possible

https://github.com/skk-dev/skktools/issues/25
Thank you for your reminder. I have provided some simple descriptions.

**Comment by Avimitin** [comment]
> Thank you for your reminder. I have provided some simple descriptions.

Simply describing what happened is totally inadequate, and conversely this can confuse the upstream. In addition to just describing config.guess file is too old, you should consider adding more content to your upstream bug report about what errors are caused by config.guess files that are too old, and why an update to config.guess file would fix them.

**Comment by XiePengHan** [comment]
> > Thank you for your reminder. I have provided some simple descriptions.
> 
> Simply describing what happened is totally inadequate, and conversely this can confuse the upstream. In addition to just describing config.guess file is too old, you should consider adding more content to your upstream bug report about what errors are caused by config.guess files that are too old, and why an update to config.guess file would fix them.

Thank you for your guidance. I added an error report regarding this issue, following your guidance.

**Comment by Avimitin** [comment]
> I added an error report regarding this issue

Consider wrap the log in a code block. This could help increasing readability and help you gain positive review from upstream.

**Comment by XiePengHan** [comment]
> > I added an error report regarding this issue
> 
> Consider wrapping the config.guess error log in a code block. This could help increasing readability and help you gain positive review from upstream.

That was my oversight. Thank you for pointing it out

**Comment by Avimitin** [comment]
You can also take this issue as a great config.guess related bug report example: `https://github.com/libunwind/libunwind/issues/654`.

**Comment by XiePengHan** [comment]
> You can also take this issue as a great config.guess related bug report example: `https://github.com/libunwind/libunwind/issues/654`.

This is a very good example, and I have made the necessary modifications following your example. If there are still any issues, please feel free to contact me, and I will make corrections promptly. Thank you very much.

**Pull request merged**
