### PR TITLE
addpatch:paperkey

### PR DESCRIPTION
**Pull request by yuuu0724**
Update config.{guess,sub}. Upstreamed to https://github.com/dmshaw/paperkey/issues/12

### CODE REVIEW

**Comment by r-value** [comment]
Instead of re-creating the whole branch and PR, you can just push to the branch of your PR to make modification. Use rebase operation or amend option of git and then make a forced push to the target branch.

**Comment by yuuu0724** [comment]
> 您无需重新创建整个分支和 PR，只需推送到 PR 的分支进行修改即可。使用rebase操作或者修改git的选项，然后强制push到目标分支。



> 您需要重新创建整个分支和 PR，只需创建一个到 PR 的分支进行修改即可。使用 rebase 操作或者修改 git 的选项，然后强制推送到目标分支。

Okay, I'll pay attention next time, and I've already reported the file issues to the upstream.

**Comment by yuuu0724** [comment]
Update config.{guess,sub}. [Upstreamed to](https://github.com/dmshaw/paperkey/issues/12)

**Comment by yuuu0724** [comment]
Update config.{guess,sub}. Upstreamed to [Please update outdated config.{guess,sub} in release tarball #12](url)

**Comment by yuuu0724** [comment]
Update config.{guess,sub}. Upstreamed to [https://github.com/dmshaw/paperkey/issues/12](url)

**Comment by yuuu0724** [comment]
Update config.{guess,sub}. Upstreamed to[https://github.com/dmshaw/paperkey/issues/12](url)

**Pull request merged**
