### PR TITLE
addpkg: libemf

### PR DESCRIPTION
**Pull request by r-value**

### CODE REVIEW

**Comment by XieJiSS** [comment]
Would you please consider also submitting the patch to upstream? Thanks!

**Comment by r-value** [comment]
No bug tracker nor mailing list is available for this project.

**Comment by Xeonacid** [comment]
> No bug tracker nor mailing list is available for this project.

https://sourceforge.net/p/libemf/mailman/libemf-devel/ (or libemf-devel@lists.sourceforge.net) shown on https://libemf.sourceforge.net/

**Comment by r-value** [comment]
> > No bug tracker nor mailing list is available for this project.
> 
> https://sourceforge.net/p/libemf/mailman/libemf-devel/ (or [libemf-devel@lists.sourceforge.net](mailto:libemf-devel@lists.sourceforge.net)) shown on https://libemf.sourceforge.net/

Sourceforge: This list is closed, nobody may subscribe to it.

**Pull request merged**
