### PR TITLE
upgpatch: rust

### PR DESCRIPTION
**Pull request by kxxt**
Fix rotten patch.

### CODE REVIEW

**Comment by kxxt** [comment]
I am hitting this error on my build machine. 

```
running: "/usr/bin/musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=rv64gc" "-mabi=lp64d" "-m
cmodel=medany" "-march=rv64gc" "-mabi=lp64d" "-O2" "-pipe" "-fno-plt" "-fexceptions" "-Wp,-D_FORTIFY_SOURCE=2" "-Wfo
rmat" "-Werror=format-security" "-fstack-clash-protection" "-I" "/build/rust/src/rustc-1.68.0-src/src/llvm-project/l
ibunwind/include" "-nostdinc++" "-fno-exceptions" "-fno-rtti" "-fstrict-aliasing" "-funwind-tables" "-fvisibility=hi
dden" "-std=c++11" "-fvisibility-global-new-delete-hidden" "-D_LIBUNWIND_DISABLE_VISIBILITY_ANNOTATIONS" "-o" "/buil
d/rust/src/rustc-1.68.0-src/build/riscv64gc-unknown-linux-musl/native/libunwind/Unwind-EHABI.o" "-c" "/build/rust/sr
c/rustc-1.68.0-src/src/llvm-project/libunwind/src/Unwind-EHABI.cpp"
cargo:warning=cc1plus: error: unrecognized command-line option ‘-fvisibility-global-new-delete-hidden’
exit status: 1
```

It seems unrelated to the patch.

Any advice is appreciated since it takes too long to build `rust`.

**Comment by kxxt** [comment]
Commenting this line made the build pass but I doubt if it is the right solution.

```
src/rustc-1.68.0-src/src/bootstrap/native.rs
1256:        //cpp_cfg.flag_if_supported("-fvisibility-global-new-delete-hidden");
```

**Comment by kxxt** [comment]
It is odd that if I build the 1:1.67.1-1 version of the PKGBUILD with the patch from this repo, the same error occurs.

**Comment by kxxt** [comment]
I have confirmed that this is caused by a bug in `cc` crate which is already fixed by https://github.com/rust-lang/cc-rs/pull/757

I will make a PR to rust repo that updates their `cc` dependency to get it fixed.

**Comment by r-value** [comment]
Cannot reproduce on RISC-V hardware. I think the PR is ready to merge.

**Review by r-value — APPROVED** [review]
Builds fine on RISC-V hardware.

**Pull request merged**
