### PR TITLE
qemu-user-blacklist:Segmentation fault

### PR DESCRIPTION
**Pull request by XiePengHan**
There was a segment fault in the running code, but it worked fine on other systems.

### CODE REVIEW

**Comment by Xeonacid** [comment]
Although [the failing log](https://archriscv.felixc.at/.status/log.htm?url=logs/git-repair/git-repair-1.20220404-75.log) seems strange, I'm pretty sure that this patch, which just do a `cd`, cannot fix the error.
Please make a deeper investigation to find the true reason. Thanks! :)

**Comment by Xeonacid** [comment]
And this PR seems not adding the package to qemu-user-blacklist as the title says.

**Comment by xctan** [comment]
This repository *contains patches on top of Arch Linux package sources* and is RISC-V specific. Please submit only relevant and functional patches here via PR, not just reporting your problem or asking for help. As for generic issues not limited to RISC-V, you should directly report them to our upstream. If you are unfamiliar with our workflow, as shown in the title of your PR, you could carefully read [this manual](https://riscv-notes.sh1mar.in/docs/guide/PR-guide/).

**Comment by r-value** [comment]
Just noticed that you have pushed a commit of another package here. Please submit every  patch in an individual PR.

**Comment by XiePengHan** [comment]
> Just noticed that you have pushed a commit of another package here. Please submit every patch in an individual PR.

I'm sorry. It's my fault. I will pay attention in the future.

**Pull request closed without merging**
