### PR TITLE
addpatch: skia-sharp

### PR DESCRIPTION
**Pull request by kxxt**
Use system gn & ninja.

### CODE REVIEW

**Comment by Xeonacid** [comment]
I'm wondering why Arch don't use the system ones? (It seems intentional since they set $PATH.)

**Comment by kxxt** [comment]
> I'm wondering why Arch don't use the system ones? (It seems intentional since they set $PATH.)

Previously this package has the following mark:

> The package require the Google internal gn executable. We need to downloaded it from it's internal compile server but there is not RISC-V64 compatible binary on the download server.  They make some modification in the executable so the extra/gn is not usable for this package.

I guess that's the reason. But now oss gn can setup the build without trouble. 

And the changes in this patch does not fit into an Arch bug report because there's no FTBFS on x86_64 side. No need to bother the package maintainers.

**Comment by Xeonacid** [comment]
> And the changes in this patch does not fit into an Arch bug report because there's no FTBFS on x86_64 side. No need to bother the package maintainers.

Actually I don't think so. Using system makedepends should be an enhancement.

**Comment by kxxt** [comment]
> > And the changes in this patch does not fit into an Arch bug report because there's no FTBFS on x86_64 side. No need to bother the package maintainers.
> 
> Actually I don't think so. Using system makedepends should be an enhancement.

Yes, it is an enhancement **that doesn't affect the build output**. I don't think it deserve a **bug** report. It is neither a bug nor a feature request. We could submit these things when Arch opens the merge request feature for packages on their gitlab.

**Comment by r-value** [comment]
Actually I think it *is* a bug -- it's wasting user's disk space. It deserves a report to inform Arch team or at least be aware of the package maintainer's intention. It looks odd so there must be a strong reason to do so.

**Comment by kxxt** [comment]
> Actually I think it _is_ a bug -- it's wasting user's disk space. It deserves a report to inform Arch team or at least be aware of the package maintainer's intention. It looks odd so there must be a strong reason to do so.

Actually adding gn and ninja to makedepends takes extra disk space. The prebuilt version is always there unless we go out of our way to patch depot_tools. Feel free to submit a ticket if you insist :)

**Comment by felixonmars** [comment]
I have mixed feelings here because the current x86_64 approach does look disgusting to me. They may have their reasoning though :/

**Pull request merged**
