### PR TITLE
addpkg: mupdf

### PR DESCRIPTION
**Pull request by XiePengHan**
Update sha256sums

### CODE REVIEW

**Comment by r-value** [comment]
Checksum mismatches should be reported to Arch Linux.

**Comment by XiePengHan** [comment]
> Checksum mismatches should be reported to Arch Linux. Closing for now.

Thank you for the reminder. Do I need to submit a branch after completing the report?

**Comment by XiePengHan** [comment]
> Update sha256sums

Thank you for your patient guidance. I have reported it to Arch https://bugs.archlinux.org/task/80197. If there are still errors, please contact me and I will correct them in time.

**Comment by Xeonacid** [comment]
> > Update sha256sums
> 
> Thank you for your patient guidance. I have reported it to Arch [bugs.archlinux.org/task/80197](https://bugs.archlinux.org/task/80197). If there are still errors, please contact me and I will correct them in time.

You forgot to ENTER SUMMARY as title there.

**Comment by XiePengHan** [comment]
> > > Update sha256sums
> > 
> > 
> > Thank you for your patient guidance. I have reported it to Arch [bugs.archlinux.org/task/80197](https://bugs.archlinux.org/task/80197). If there are still errors, please contact me and I will correct them in time.
> 
> You forgot to ENTER SUMMARY as title there.

It is my fault. https://bugs.archlinux.org/task/80198

**Pull request closed without merging**
