### PR TITLE
addpkg: libisoburn

### PR DESCRIPTION
**Pull request by yuxuan9982**

### CODE REVIEW

**Comment by Xeonacid** [comment]
Please report to upstream to let them update config.guess/sub. :)

**Comment by yuxuan9982** [comment]
how to report to upstream, i am a noob :(



---Original---
From: ***@***.***&gt;
Date: Sat, Nov 4, 2023 16:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [felixonmars/archriscv-packages] addpkg: libisoburn (PR #3219)




 
Please report to upstream to let them update config.guess/sub. :)

**Comment by r-value** [comment]
Please read our wiki/manual carefully before making contribution

**Comment by yuxuan9982** [comment]
> Please read our wiki/manual carefully before making contribution

thanks for suggesting, but I am still stuck because the upstream link https://dev.lovelyhq.com/libburnia/libisoburn seems to require an account to have the permission to report an issue but it does not have a registation button,  what should I do...

**Comment by r-value** [comment]
Personally I think you should contact the primary maintainer of the code repo directly through e-mail or other contact info provided.

**Comment by yuxuan9982** [comment]
> Personally I think you should contact the primary maintainer of the code repo directly through e-mail or other contact info provided.

ok, thanks

**Comment by Xeonacid** [comment]
Superseded by #3639, closing.

**Pull request closed without merging**
