### PR TITLE
addpatch: ogre

### PR DESCRIPTION
**Pull request by sihuan**
Change the default timeout to avoid timeouts on check().
It takes about 3000s to pass `TestContext_OpenGLRenderingSubsystem` on  HiFive Unmatched.

[Patch has been submitted upstream](https://github.com/OGRECave/ogre/pull/2816)

### CODE REVIEW

**Comment by Xeonacid** [comment]
Upstream bumped version just now, and the patch needs bump.

**Comment by sihuan** [comment]
Updated patch to follow upstream.

**Comment by sihuan** [comment]
Updated patch to follow upstream.

**Comment by Xeonacid** [comment]
It builds fine now, closing.

**Pull request closed without merging**
