### PR TITLE
addpkg: libfreexl

### PR DESCRIPTION
**Pull request by XiePengHan**

### CODE REVIEW

**Comment by r-value** [comment]
We prefer a patch of minimum changes to reduce maintenance workloads. Please exclude all superfluous changes.
Also can you give a brief explanation of the motivation of your changes? It can help us reviewing your patch.

**Comment by XiePengHan** [comment]
> 我们更喜欢使用最少的更改补丁来减少维护工作量。请排除所有多余的更改。另外，您能简要解释一下您更改的动机吗？它可以帮助我们审查您的补丁。

依赖那里确实有更多的更改(因为我需要调试以及之前的试错)，错误是因为configure脚本无法识别riscv64-linux作为有效的构建系统类型。这通常是由于缺少对目标体系结构的支持所致

**Comment by XiePengHan** [comment]
> We prefer a patch of minimum changes to reduce maintenance workloads. Please exclude all superfluous changes. Also can you give a brief explanation of the motivation of your changes? It can help us reviewing your patch.

Dependencies there did have more changes (because I needed to debug as well as trial and error before).The error is because the configure script does not recognize riscv64-linux as a valid build system type. This is usually due to a lack of support for the target architecture

**Comment by XieJiSS** [comment]
We usually fix this type of errors in another way: https://github.com/felixonmars/archriscv-packages/wiki/%E6%88%91%E4%BB%AC%E7%9A%84%E5%B7%A5%E4%BD%9C%E4%B9%A0%E6%83%AF#configguess-unable-to-guess-system-type

**Comment by XiePengHan** [comment]
> We usually fix this type of error in another way: https://github.com/felixonmars/archriscv-packages/wiki/%E6%88%91%E4%BB%AC%E7%9A%84%E5%B7%A5%E4%BD%9C%E4%B9%A0%E6%83%AF#configguess-unable-to-guess-system-type

Thanks for the guidance of seniors, I have modified according to the information you sent.

**Comment by xctan** [comment]
We usually merge PRs by rebasing, not squashing, which means that *all* your commits in the PR would be appended to the master branch instead of a single merge commit. Please consider if it is appropriate to make such a minor change in numerous commits.
* If you need to correct your previous commit, try `git commit --amend` to amend it.
* If you want to merge several commits on your side, please learn about `git rebase` to squash them into one single commit. And then, you should use `git push --force` to sync with your branch on GitHub.
* If you are unfamiliar with version control using git and want to learn more about it, *The Missing Semester of Your CS Education* is a good start.

**Pull request closed without merging**
