### PR TITLE
devtools-riscv64: use https://riscv.mirror.pkgbuild.com as default mirror

### PR DESCRIPTION
**Pull request by CoelacanthusHex**
Get better performance everywhere. And the mirror synchronization frequency is high enough.

As we do in rootfs.

### CODE REVIEW

**Comment by felixonmars** [comment]
This would unfortunately break rebuilds though. Until we have a way to override the mirrors per builder, the default mirror is still unfortunately the only choice.

**Comment by CoelacanthusHex** [comment]
Ok, I will close it and open an issue to track it.

**Comment by XieJiSS** [comment]
I'm wondering why this would break rebuilds, is it related to the lag between the default site and mirrors?

**Comment by felixonmars** [comment]
> I'm wondering why this would break rebuilds, is it related to the lag between the default site and mirrors?

Yes. Builders using a not up-to-date may rebuild against an old version of a just-updated dependency.

**Pull request closed without merging**
