### PR TITLE
addpatch: reiserfsprogs

### PR DESCRIPTION
**Pull request by Avimitin**
Fix config.guess can not guess build type error.

Signed-off-by: Avimitin <avimitin@gmail.com>

### CODE REVIEW

**Comment by felixonmars** [comment]
Please also notify upstream so hopefully we don't need this in future releases.

**Comment by bastianplettner** [comment]
There is a post on the `reiserfs-devel` mailing list about this issue.

https://www.spinics.net/lists/reiserfs-devel/msg07057.html

**Comment by felixonmars** [comment]
That's great. Thanks!

**Comment by Avimitin** [comment]
@felixonmars 我还在等 LKML 那边更新（

**Comment by Avimitin** [comment]
This can also be tracked on LKML: https://lore.kernel.org/lkml/3e450ff5-f084-4a33-bff7-4ef1061d1f30@iscas.ac.cn/

**Pull request merged**
