### PR TITLE
addpatch: virt-what 1.25-2

### PR DESCRIPTION
**Pull request by qyl27**
Unable to report because this package is abandoned.

### CODE REVIEW

**Comment by Xeonacid** [comment]
Could you kindly clarify where it indicates that this package has been abandoned? I saw it was last [released on 2024-08-31](https://people.redhat.com/~rjones/virt-what/files/).

**Comment by qyl27** [comment]
Oh, sorry, that's my fault.

**Comment by Xeonacid** [comment]
Hey, there is no need to say sorry or close the PR! We can merge this PR first, in the meantime, you may report this to upstream.

**Comment by qyl27** [comment]
No, it caused by ArchLinux not being up-to-date that I haven't noticed, this pr is for 1.25-2, but the newest is 1.27.  
I have flagged it in ArchLinux packages, it may need to change after they update the build script.

**Comment by qyl27** [comment]
ArchLinux updated 1.27-1, no need this PR now.

**Pull request closed without merging**
